<?php
/**
 * TestCase
 * @author tan bing
 * @date 2021-06-03 9:57
 */
namespace Tanbing\BlogPackage\Tests;

use Tanbing\BlogPackage\BlogPackageServiceProvider;
use Orchestra\Testbench\TestCase as TestCases;

class TestCase extends TestCases
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

//        $this->withFactories(__DIR__.'/../database/factories');
    }

    public function getPackageProviders($app)
    {
        return [
            BlogPackageServiceProvider::class,
        ];
    }

    public function getEnvironmentSetUp($app)
    {
        // perform environment setup
        // import the CreatePostsTable class from the migration
//        include_once __DIR__ . '/../database/migrations/create_posts_table.php';

        // run the up() method of that migration class
//        (new \CreatePostsTable)->up();
    }
}